/**
 * TagSelector Core - TaxonomyIndex Types
 * Version: 1.3.1
 *
 * TaxonomyIndex is the pre-built index for efficient querying and sorting.
 *
 * NAMING LOCK (禁止重命名):
 * - Field names: childrenOf, siblingOrdinal, sortPathCache
 * - These names are locked and must not be renamed.
 */

import type { NodeId, TagNode } from './node.js';
import type { Taxonomy } from './taxonomy.js';

/**
 * Pre-built index for efficient taxonomy operations.
 *
 * FIELD DEFINITIONS:
 * - byId: Quick lookup by node ID
 * - childrenOf: Children of each parent, pre-sorted by compareNodes
 * - siblingOrdinal: Sibling order number (0..n-1) for each node
 * - sortPathCache: Pre-computed sortPath (ordinal sequence from root to node)
 */
export interface TaxonomyIndex {
  /** The source taxonomy */
  taxonomy: Taxonomy;

  /** Quick lookup: NodeId -> TagNode */
  byId: Map<NodeId, TagNode>;

  /**
   * Children of each parent, pre-sorted by compareNodes.
   * Key: parentId (null for root nodes)
   * Value: Array of child NodeIds in sorted order
   */
  childrenOf: Map<NodeId | null, NodeId[]>;

  /**
   * Sibling ordinal (兄弟序号) for each node.
   * This is the 0-based index within its parent's sorted children.
   * Generated by index-builder based on compareNodes order.
   */
  siblingOrdinal: Map<NodeId, number>;

  /**
   * Pre-computed sortPath for each node.
   * sortPath = [ancestor1.ordinal, ancestor2.ordinal, ..., self.ordinal]
   * Used for final sorting in sortByUserOrder.
   */
  sortPathCache: Map<NodeId, number[]>;
}

